Cypress.Commands.add('allProducts', () => {
    cy.fixture('allProduct').then((data) => {
        Cypress.on('uncaught:exception', (err) => {
            console.log('ERROR CAUGHT:', err.message)
            if (err.message.includes('addEventListener')) {
                return false
            }
        })
        cy.contains('All Products', { timeout: 10000 }).click()
        cy.get('#addProductBtn', { timeout: 10000 }).click()
        cy.wait(2000)

        cy.get('body').then($body => {
            cy.log('productName count: ' + $body.find('#productName').length)
        })
       cy.get('#productName').click({force:true})
        // cy.contains('Product Description').type(data.productDescription)
        // cy.get('#sku').type(data.skuValue)
        // cy.get('#itemType').select(data.itemType)
        // cy.get('#classSubClass-popup-input').click()
        // cy.get('#classSubClass-popup-dropdown')
        //     .should('be.visible')
        //     .contains('.custom-dropdown-item', data.class)
        //     .click() 
        // cy.get('#SubClass-popup-input').click()
        // cy.get('#SubClass-popup-dropdown')
        //     .should('be.visible')
        //     .contains('.custom-dropdown-item', data.subClass)
        //     .click({ force: true })
        // cy.log(data.subClass)
        // cy.contains('Available Quantity').type(data.availableQuantity)
        // cy.get('#binNumber').type(data.binNumber)
        // cy.get('#singleParentCheckbox').click({ force: true })
        // cy.get('#singlePurchasePrice').type(data.estCostPrice)
        // cy.get('#singleBasePrice').type(data.sellingPrice)
        // cy.get('#singleQuantity').type(data.quantityinHand)
        // cy.get('#singleReorderPoint').type(data.reorderPoint)
        // cy.get('#quantityInput_single').type(data.quantity)
        // cy.get('#priceInput_single').type(data.pricing)
        // cy.get('[onclick="addQuantityPriceRow_single()"]').click()
        // cy.get('#selectRule_single').select(data.selectRule)
        // // cy.contains('Browse image').click({force:true})
        // cy.contains('Browse image')
        //     .selectFile(`cypress/fixtures/${data.imageFileName}`, { force: true })
        // cy.get('#Vendor-popup-input').click()
        // cy.get('#Vendor-popup-dropdown')
        //     .contains('.custom-dropdown-item', data.vendor)
        //     .click()

        // cy.get('#Brand-popup-input').click()

        // cy.get('#Brand-popup-dropdown')
        //     .contains('.custom-dropdown-item', data.brand)
        //     .click()
        // cy.get('input.keyFeatureInput')
        //     .should('be.visible')
        //     .type(data.keyFeature)
        // cy.contains('Display On Web').click({ force: true })
        // cy.contains('Save', { timeout: 2000 }).click({ force: true })

    })
})